import type { Metadata } from "next";
import { Geist, Geist_Mono, Lato, Merriweather, Roboto_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const robotoMonoRobotoMono = Roboto_Mono({subsets:['latin','latin-ext','cyrillic','cyrillic-ext','greek','vietnamese'],weight:['100','200','300','400','500','600','700'],variable:'--font-roboto-mono'});

const merriweatherMerriweather = Merriweather({subsets:['cyrillic','cyrillic-ext','latin','latin-ext','vietnamese'],weight:['300','400','500','600','700','800','900'],variable:'--font-merriweather'});

const latoLato = Lato({subsets:['latin','latin-ext'],weight:['100','300','400','700','900'],variable:'--font-lato'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, latoLato.variable, merriweatherMerriweather.variable, robotoMonoRobotoMono.variable)}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
